<html>
    <head>
        <title>Account Registration</title>
    </head>
    <body>
        <p>Hi ${name},</p>
        <br />
        <p>Kindly find below Your created account details </p>
        <p>UserName - ${username}</p>
        <p>Password - ${password}</p>

        <p>click on this link to complete your Account Registration</p>
        <P>${verifylink} </P>

        <p>Thanks</p>

    </body>
</html>